//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SREmulator.Localizations {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SREmulator.Localizations.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Acheron 的本地化字符串。
        /// </summary>
        internal static string Acheron {
            get {
                return ResourceManager.GetString("Acheron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ADreamScentedInWheat 的本地化字符串。
        /// </summary>
        internal static string ADreamScentedInWheat {
            get {
                return ResourceManager.GetString("ADreamScentedInWheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adversarial 的本地化字符串。
        /// </summary>
        internal static string Adversarial {
            get {
                return ResourceManager.GetString("Adversarial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AfterTheCharmonyFall 的本地化字符串。
        /// </summary>
        internal static string AfterTheCharmonyFall {
            get {
                return ResourceManager.GetString("AfterTheCharmonyFall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aglaea 的本地化字符串。
        /// </summary>
        internal static string Aglaea {
            get {
                return ResourceManager.GetString("Aglaea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AGroundedAscent 的本地化字符串。
        /// </summary>
        internal static string AGroundedAscent {
            get {
                return ResourceManager.GetString("AGroundedAscent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlongThePassingShore 的本地化字符串。
        /// </summary>
        internal static string AlongThePassingShore {
            get {
                return ResourceManager.GetString("AlongThePassingShore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amber 的本地化字符串。
        /// </summary>
        internal static string Amber {
            get {
                return ResourceManager.GetString("Amber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anaxa 的本地化字符串。
        /// </summary>
        internal static string Anaxa {
            get {
                return ResourceManager.GetString("Anaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AnInstantBeforeAGaze 的本地化字符串。
        /// </summary>
        internal static string AnInstantBeforeAGaze {
            get {
                return ResourceManager.GetString("AnInstantBeforeAGaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archer 的本地化字符串。
        /// </summary>
        internal static string Archer {
            get {
                return ResourceManager.GetString("Archer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argenti 的本地化字符串。
        /// </summary>
        internal static string Argenti {
            get {
                return ResourceManager.GetString("Argenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arlan 的本地化字符串。
        /// </summary>
        internal static string Arlan {
            get {
                return ResourceManager.GetString("Arlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arrows 的本地化字符串。
        /// </summary>
        internal static string Arrows {
            get {
                return ResourceManager.GetString("Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASecretVow 的本地化字符串。
        /// </summary>
        internal static string ASecretVow {
            get {
                return ResourceManager.GetString("ASecretVow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Asta 的本地化字符串。
        /// </summary>
        internal static string Asta {
            get {
                return ResourceManager.GetString("Asta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AThanklessCoronation 的本地化字符串。
        /// </summary>
        internal static string AThanklessCoronation {
            get {
                return ResourceManager.GetString("AThanklessCoronation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATrailOfBygoneBlood 的本地化字符串。
        /// </summary>
        internal static string ATrailOfBygoneBlood {
            get {
                return ResourceManager.GetString("ATrailOfBygoneBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aventurine 的本地化字符串。
        /// </summary>
        internal static string Aventurine {
            get {
                return ResourceManager.GetString("Aventurine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bailu 的本地化字符串。
        /// </summary>
        internal static string Bailu {
            get {
                return ResourceManager.GetString("Bailu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BaptismOfPureThought 的本地化字符串。
        /// </summary>
        internal static string BaptismOfPureThought {
            get {
                return ResourceManager.GetString("BaptismOfPureThought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BeforeDawn 的本地化字符串。
        /// </summary>
        internal static string BeforeDawn {
            get {
                return ResourceManager.GetString("BeforeDawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BeforeTheTutorialMissionStarts 的本地化字符串。
        /// </summary>
        internal static string BeforeTheTutorialMissionStarts {
            get {
                return ResourceManager.GetString("BeforeTheTutorialMissionStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BlackSwan 的本地化字符串。
        /// </summary>
        internal static string BlackSwan {
            get {
                return ResourceManager.GetString("BlackSwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blade 的本地化字符串。
        /// </summary>
        internal static string Blade {
            get {
                return ResourceManager.GetString("Blade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boothill 的本地化字符串。
        /// </summary>
        internal static string Boothill {
            get {
                return ResourceManager.GetString("Boothill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoundlessChoreo 的本地化字符串。
        /// </summary>
        internal static string BoundlessChoreo {
            get {
                return ResourceManager.GetString("BoundlessChoreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BrighterThanTheSun 的本地化字符串。
        /// </summary>
        internal static string BrighterThanTheSun {
            get {
                return ResourceManager.GetString("BrighterThanTheSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bronya 的本地化字符串。
        /// </summary>
        internal static string Bronya {
            get {
                return ResourceManager.GetString("Bronya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ButTheBattleIsntOver 的本地化字符串。
        /// </summary>
        internal static string ButTheBattleIsntOver {
            get {
                return ResourceManager.GetString("ButTheBattleIsntOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CarveTheMoonWeaveTheClouds 的本地化字符串。
        /// </summary>
        internal static string CarveTheMoonWeaveTheClouds {
            get {
                return ResourceManager.GetString("CarveTheMoonWeaveTheClouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Castorice 的本地化字符串。
        /// </summary>
        internal static string Castorice {
            get {
                return ResourceManager.GetString("Castorice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cerydra 的本地化字符串。
        /// </summary>
        internal static string Cerydra {
            get {
                return ResourceManager.GetString("Cerydra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chorus 的本地化字符串。
        /// </summary>
        internal static string Chorus {
            get {
                return ResourceManager.GetString("Chorus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cipher 的本地化字符串。
        /// </summary>
        internal static string Cipher {
            get {
                return ResourceManager.GetString("Cipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clara 的本地化字符串。
        /// </summary>
        internal static string Clara {
            get {
                return ResourceManager.GetString("Clara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CollapsingSky 的本地化字符串。
        /// </summary>
        internal static string CollapsingSky {
            get {
                return ResourceManager.GetString("CollapsingSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConcertForTwo 的本地化字符串。
        /// </summary>
        internal static string ConcertForTwo {
            get {
                return ResourceManager.GetString("ConcertForTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cornucopia 的本地化字符串。
        /// </summary>
        internal static string Cornucopia {
            get {
                return ResourceManager.GetString("Cornucopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CruisingInTheStellarSea 的本地化字符串。
        /// </summary>
        internal static string CruisingInTheStellarSea {
            get {
                return ResourceManager.GetString("CruisingInTheStellarSea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DanceAtSunset 的本地化字符串。
        /// </summary>
        internal static string DanceAtSunset {
            get {
                return ResourceManager.GetString("DanceAtSunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DanceDanceDance 的本地化字符串。
        /// </summary>
        internal static string DanceDanceDance {
            get {
                return ResourceManager.GetString("DanceDanceDance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DanHeng 的本地化字符串。
        /// </summary>
        internal static string DanHeng {
            get {
                return ResourceManager.GetString("DanHeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DanHengImbibitorLunae 的本地化字符串。
        /// </summary>
        internal static string DanHengImbibitorLunae {
            get {
                return ResourceManager.GetString("DanHengImbibitorLunae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DanHengPermansorTerrae 的本地化字符串。
        /// </summary>
        internal static string DanHengPermansorTerrae {
            get {
                return ResourceManager.GetString("DanHengPermansorTerrae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DartingArrow 的本地化字符串。
        /// </summary>
        internal static string DartingArrow {
            get {
                return ResourceManager.GetString("DartingArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataBank 的本地化字符串。
        /// </summary>
        internal static string DataBank {
            get {
                return ResourceManager.GetString("DataBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DayOneOfMyNewLife 的本地化字符串。
        /// </summary>
        internal static string DayOneOfMyNewLife {
            get {
                return ResourceManager.GetString("DayOneOfMyNewLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Defense 的本地化字符串。
        /// </summary>
        internal static string Defense {
            get {
                return ResourceManager.GetString("Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DestinysThreadsForewoven 的本地化字符串。
        /// </summary>
        internal static string DestinysThreadsForewoven {
            get {
                return ResourceManager.GetString("DestinysThreadsForewoven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DreamsMontage 的本地化字符串。
        /// </summary>
        internal static string DreamsMontage {
            get {
                return ResourceManager.GetString("DreamsMontage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DreamvilleAdventure 的本地化字符串。
        /// </summary>
        internal static string DreamvilleAdventure {
            get {
                return ResourceManager.GetString("DreamvilleAdventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DrRatio 的本地化字符串。
        /// </summary>
        internal static string DrRatio {
            get {
                return ResourceManager.GetString("DrRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EarthlyEscapade 的本地化字符串。
        /// </summary>
        internal static string EarthlyEscapade {
            get {
                return ResourceManager.GetString("EarthlyEscapade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EchoesOfTheCoffin 的本地化字符串。
        /// </summary>
        internal static string EchoesOfTheCoffin {
            get {
                return ResourceManager.GetString("EchoesOfTheCoffin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EpochEtchedInGoldenBlood 的本地化字符串。
        /// </summary>
        internal static string EpochEtchedInGoldenBlood {
            get {
                return ResourceManager.GetString("EpochEtchedInGoldenBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EternalCalculus 的本地化字符串。
        /// </summary>
        internal static string EternalCalculus {
            get {
                return ResourceManager.GetString("EternalCalculus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evernight 的本地化字符串。
        /// </summary>
        internal static string Evernight {
            get {
                return ResourceManager.GetString("Evernight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EyesOfThePrey 的本地化字符串。
        /// </summary>
        internal static string EyesOfThePrey {
            get {
                return ResourceManager.GetString("EyesOfThePrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feixiao 的本地化字符串。
        /// </summary>
        internal static string Feixiao {
            get {
                return ResourceManager.GetString("Feixiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fermata 的本地化字符串。
        /// </summary>
        internal static string Fermata {
            get {
                return ResourceManager.GetString("Fermata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FinalVictor 的本地化字符串。
        /// </summary>
        internal static string FinalVictor {
            get {
                return ResourceManager.GetString("FinalVictor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FineFruit 的本地化字符串。
        /// </summary>
        internal static string FineFruit {
            get {
                return ResourceManager.GetString("FineFruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firefly 的本地化字符串。
        /// </summary>
        internal static string Firefly {
            get {
                return ResourceManager.GetString("Firefly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlameOfBloodBlazeMyPath 的本地化字符串。
        /// </summary>
        internal static string FlameOfBloodBlazeMyPath {
            get {
                return ResourceManager.GetString("FlameOfBloodBlazeMyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlamesAfar 的本地化字符串。
        /// </summary>
        internal static string FlamesAfar {
            get {
                return ResourceManager.GetString("FlamesAfar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowingNightglow 的本地化字符串。
        /// </summary>
        internal static string FlowingNightglow {
            get {
                return ResourceManager.GetString("FlowingNightglow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ForTomorrowsJourney 的本地化字符串。
        /// </summary>
        internal static string ForTomorrowsJourney {
            get {
                return ResourceManager.GetString("ForTomorrowsJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fugue 的本地化字符串。
        /// </summary>
        internal static string Fugue {
            get {
                return ResourceManager.GetString("Fugue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FuXuan 的本地化字符串。
        /// </summary>
        internal static string FuXuan {
            get {
                return ResourceManager.GetString("FuXuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gallagher 的本地化字符串。
        /// </summary>
        internal static string Gallagher {
            get {
                return ResourceManager.GetString("Gallagher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GeniusesGreetings 的本地化字符串。
        /// </summary>
        internal static string GeniusesGreetings {
            get {
                return ResourceManager.GetString("GeniusesGreetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GeniusesRepose 的本地化字符串。
        /// </summary>
        internal static string GeniusesRepose {
            get {
                return ResourceManager.GetString("GeniusesRepose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gepard 的本地化字符串。
        /// </summary>
        internal static string Gepard {
            get {
                return ResourceManager.GetString("Gepard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GoodNightAndSleepWell 的本地化字符串。
        /// </summary>
        internal static string GoodNightAndSleepWell {
            get {
                return ResourceManager.GetString("GoodNightAndSleepWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guinaifen 的本地化字符串。
        /// </summary>
        internal static string Guinaifen {
            get {
                return ResourceManager.GetString("Guinaifen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hanya 的本地化字符串。
        /// </summary>
        internal static string Hanya {
            get {
                return ResourceManager.GetString("Hanya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Herta 的本地化字符串。
        /// </summary>
        internal static string Herta {
            get {
                return ResourceManager.GetString("Herta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HeyOverHere 的本地化字符串。
        /// </summary>
        internal static string HeyOverHere {
            get {
                return ResourceManager.GetString("HeyOverHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HiddenShadow 的本地化字符串。
        /// </summary>
        internal static string HiddenShadow {
            get {
                return ResourceManager.GetString("HiddenShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Himeko 的本地化字符串。
        /// </summary>
        internal static string Himeko {
            get {
                return ResourceManager.GetString("Himeko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HolidayThermaeEscapade 的本地化字符串。
        /// </summary>
        internal static string HolidayThermaeEscapade {
            get {
                return ResourceManager.GetString("HolidayThermaeEscapade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hook 的本地化字符串。
        /// </summary>
        internal static string Hook {
            get {
                return ResourceManager.GetString("Hook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Huohuo 的本地化字符串。
        /// </summary>
        internal static string Huohuo {
            get {
                return ResourceManager.GetString("Huohuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hyacine 的本地化字符串。
        /// </summary>
        internal static string Hyacine {
            get {
                return ResourceManager.GetString("Hyacine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hysilens 的本地化字符串。
        /// </summary>
        internal static string Hysilens {
            get {
                return ResourceManager.GetString("Hysilens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IfTimeWereAFlower 的本地化字符串。
        /// </summary>
        internal static string IfTimeWereAFlower {
            get {
                return ResourceManager.GetString("IfTimeWereAFlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IncessantRain 的本地化字符串。
        /// </summary>
        internal static string IncessantRain {
            get {
                return ResourceManager.GetString("IncessantRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IndeliblePromise 的本地化字符串。
        /// </summary>
        internal static string IndeliblePromise {
            get {
                return ResourceManager.GetString("IndeliblePromise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InherentlyUnjustDestiny 的本地化字符串。
        /// </summary>
        internal static string InherentlyUnjustDestiny {
            get {
                return ResourceManager.GetString("InherentlyUnjustDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InPursuitOfTheWind 的本地化字符串。
        /// </summary>
        internal static string InPursuitOfTheWind {
            get {
                return ResourceManager.GetString("InPursuitOfTheWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InTheNameOfTheWorld 的本地化字符串。
        /// </summary>
        internal static string InTheNameOfTheWorld {
            get {
                return ResourceManager.GetString("InTheNameOfTheWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InTheNight 的本地化字符串。
        /// </summary>
        internal static string InTheNight {
            get {
                return ResourceManager.GetString("InTheNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IntoTheUnreachableVeil 的本地化字符串。
        /// </summary>
        internal static string IntoTheUnreachableVeil {
            get {
                return ResourceManager.GetString("IntoTheUnreachableVeil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IShallBeMyOwnSword 的本地化字符串。
        /// </summary>
        internal static string IShallBeMyOwnSword {
            get {
                return ResourceManager.GetString("IShallBeMyOwnSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItsShowtime 的本地化字符串。
        /// </summary>
        internal static string ItsShowtime {
            get {
                return ResourceManager.GetString("ItsShowtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IVentureForthToHunt 的本地化字符串。
        /// </summary>
        internal static string IVentureForthToHunt {
            get {
                return ResourceManager.GetString("IVentureForthToHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jade 的本地化字符串。
        /// </summary>
        internal static string Jade {
            get {
                return ResourceManager.GetString("Jade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jiaoqiu 的本地化字符串。
        /// </summary>
        internal static string Jiaoqiu {
            get {
                return ResourceManager.GetString("Jiaoqiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jingliu 的本地化字符串。
        /// </summary>
        internal static string Jingliu {
            get {
                return ResourceManager.GetString("Jingliu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JingYuan 的本地化字符串。
        /// </summary>
        internal static string JingYuan {
            get {
                return ResourceManager.GetString("JingYuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JourneyForeverPeaceful 的本地化字符串。
        /// </summary>
        internal static string JourneyForeverPeaceful {
            get {
                return ResourceManager.GetString("JourneyForeverPeaceful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kafka 的本地化字符串。
        /// </summary>
        internal static string Kafka {
            get {
                return ResourceManager.GetString("Kafka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LandausChoice 的本地化字符串。
        /// </summary>
        internal static string LandausChoice {
            get {
                return ResourceManager.GetString("LandausChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LiesDanceOnTheBreeze 的本地化字符串。
        /// </summary>
        internal static string LiesDanceOnTheBreeze {
            get {
                return ResourceManager.GetString("LiesDanceOnTheBreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LifeShouldBeCastToFlames 的本地化字符串。
        /// </summary>
        internal static string LifeShouldBeCastToFlames {
            get {
                return ResourceManager.GetString("LifeShouldBeCastToFlames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lingsha 的本地化字符串。
        /// </summary>
        internal static string Lingsha {
            get {
                return ResourceManager.GetString("Lingsha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LongMayRainbowsAdornTheSky 的本地化字符串。
        /// </summary>
        internal static string LongMayRainbowsAdornTheSky {
            get {
                return ResourceManager.GetString("LongMayRainbowsAdornTheSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LongRoadLeadsHome 的本地化字符串。
        /// </summary>
        internal static string LongRoadLeadsHome {
            get {
                return ResourceManager.GetString("LongRoadLeadsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loop 的本地化字符串。
        /// </summary>
        internal static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Luka 的本地化字符串。
        /// </summary>
        internal static string Luka {
            get {
                return ResourceManager.GetString("Luka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Luocha 的本地化字符串。
        /// </summary>
        internal static string Luocha {
            get {
                return ResourceManager.GetString("Luocha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lynx 的本地化字符串。
        /// </summary>
        internal static string Lynx {
            get {
                return ResourceManager.GetString("Lynx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MakeFarewellsMoreBeautiful 的本地化字符串。
        /// </summary>
        internal static string MakeFarewellsMoreBeautiful {
            get {
                return ResourceManager.GetString("MakeFarewellsMoreBeautiful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MakeTheWorldClamor 的本地化字符串。
        /// </summary>
        internal static string MakeTheWorldClamor {
            get {
                return ResourceManager.GetString("MakeTheWorldClamor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 March7th 的本地化字符串。
        /// </summary>
        internal static string March7th {
            get {
                return ResourceManager.GetString("March7th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mediation 的本地化字符串。
        /// </summary>
        internal static string Mediation {
            get {
                return ResourceManager.GetString("Mediation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MemoriesOfThePast 的本地化字符串。
        /// </summary>
        internal static string MemoriesOfThePast {
            get {
                return ResourceManager.GetString("MemoriesOfThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MemorysCurtainNeverFalls 的本地化字符串。
        /// </summary>
        internal static string MemorysCurtainNeverFalls {
            get {
                return ResourceManager.GetString("MemorysCurtainNeverFalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MeshingCogs 的本地化字符串。
        /// </summary>
        internal static string MeshingCogs {
            get {
                return ResourceManager.GetString("MeshingCogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Misha 的本地化字符串。
        /// </summary>
        internal static string Misha {
            get {
                return ResourceManager.GetString("Misha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MomentOfVictory 的本地化字符串。
        /// </summary>
        internal static string MomentOfVictory {
            get {
                return ResourceManager.GetString("MomentOfVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moze 的本地化字符串。
        /// </summary>
        internal static string Moze {
            get {
                return ResourceManager.GetString("Moze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiplication 的本地化字符串。
        /// </summary>
        internal static string Multiplication {
            get {
                return ResourceManager.GetString("Multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MutualDemise 的本地化字符串。
        /// </summary>
        internal static string MutualDemise {
            get {
                return ResourceManager.GetString("MutualDemise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mydei 的本地化字符串。
        /// </summary>
        internal static string Mydei {
            get {
                return ResourceManager.GetString("Mydei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Natasha 的本地化字符串。
        /// </summary>
        internal static string Natasha {
            get {
                return ResourceManager.GetString("Natasha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NightOfFright 的本地化字符串。
        /// </summary>
        internal static string NightOfFright {
            get {
                return ResourceManager.GetString("NightOfFright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NightOnTheMilkyWay 的本地化字符串。
        /// </summary>
        internal static string NightOnTheMilkyWay {
            get {
                return ResourceManager.GetString("NightOnTheMilkyWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NinjaRecordSoundHunt 的本地化字符串。
        /// </summary>
        internal static string NinjaRecordSoundHunt {
            get {
                return ResourceManager.GetString("NinjaRecordSoundHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NinjutsuInscriptionDazzlingEvilbreaker 的本地化字符串。
        /// </summary>
        internal static string NinjutsuInscriptionDazzlingEvilbreaker {
            get {
                return ResourceManager.GetString("NinjutsuInscriptionDazzlingEvilbreaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NowhereToRun 的本地化字符串。
        /// </summary>
        internal static string NowhereToRun {
            get {
                return ResourceManager.GetString("NowhereToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnlySilenceRemains 的本地化字符串。
        /// </summary>
        internal static string OnlySilenceRemains {
            get {
                return ResourceManager.GetString("OnlySilenceRemains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnTheFallOfAnAeon 的本地化字符串。
        /// </summary>
        internal static string OnTheFallOfAnAeon {
            get {
                return ResourceManager.GetString("OnTheFallOfAnAeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passkey 的本地化字符串。
        /// </summary>
        internal static string Passkey {
            get {
                return ResourceManager.GetString("Passkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PastAndFuture 的本地化字符串。
        /// </summary>
        internal static string PastAndFuture {
            get {
                return ResourceManager.GetString("PastAndFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PastSelfInMirror 的本地化字符串。
        /// </summary>
        internal static string PastSelfInMirror {
            get {
                return ResourceManager.GetString("PastSelfInMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PatienceIsAllYouNeed 的本地化字符串。
        /// </summary>
        internal static string PatienceIsAllYouNeed {
            get {
                return ResourceManager.GetString("PatienceIsAllYouNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pela 的本地化字符串。
        /// </summary>
        internal static string Pela {
            get {
                return ResourceManager.GetString("Pela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PerfectTiming 的本地化字符串。
        /// </summary>
        internal static string PerfectTiming {
            get {
                return ResourceManager.GetString("PerfectTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phainon 的本地化字符串。
        /// </summary>
        internal static string Phainon {
            get {
                return ResourceManager.GetString("Phainon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pioneering 的本地化字符串。
        /// </summary>
        internal static string Pioneering {
            get {
                return ResourceManager.GetString("Pioneering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlanetaryRendezvous 的本地化字符串。
        /// </summary>
        internal static string PlanetaryRendezvous {
            get {
                return ResourceManager.GetString("PlanetaryRendezvous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PoisedToBloom 的本地化字符串。
        /// </summary>
        internal static string PoisedToBloom {
            get {
                return ResourceManager.GetString("PoisedToBloom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PostOpConversation 的本地化字符串。
        /// </summary>
        internal static string PostOpConversation {
            get {
                return ResourceManager.GetString("PostOpConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qingque 的本地化字符串。
        /// </summary>
        internal static string Qingque {
            get {
                return ResourceManager.GetString("Qingque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QuidProQuo 的本地化字符串。
        /// </summary>
        internal static string QuidProQuo {
            get {
                return ResourceManager.GetString("QuidProQuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rappa 的本地化字符串。
        /// </summary>
        internal static string Rappa {
            get {
                return ResourceManager.GetString("Rappa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReforgedRemembrance 的本地化字符串。
        /// </summary>
        internal static string ReforgedRemembrance {
            get {
                return ResourceManager.GetString("ReforgedRemembrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reminiscence 的本地化字符串。
        /// </summary>
        internal static string Reminiscence {
            get {
                return ResourceManager.GetString("Reminiscence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResolutionShinesAsPearlsOfSweat 的本地化字符串。
        /// </summary>
        internal static string ResolutionShinesAsPearlsOfSweat {
            get {
                return ResourceManager.GetString("ResolutionShinesAsPearlsOfSweat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReturnToDarkness 的本地化字符串。
        /// </summary>
        internal static string ReturnToDarkness {
            get {
                return ResourceManager.GetString("ReturnToDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RiverFlowsInSpring 的本地化字符串。
        /// </summary>
        internal static string RiverFlowsInSpring {
            get {
                return ResourceManager.GetString("RiverFlowsInSpring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Robin 的本地化字符串。
        /// </summary>
        internal static string Robin {
            get {
                return ResourceManager.GetString("Robin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RuanMei 的本地化字符串。
        /// </summary>
        internal static string RuanMei {
            get {
                return ResourceManager.GetString("RuanMei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saber 的本地化字符串。
        /// </summary>
        internal static string Saber {
            get {
                return ResourceManager.GetString("Saber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sagacity 的本地化字符串。
        /// </summary>
        internal static string Sagacity {
            get {
                return ResourceManager.GetString("Sagacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SailingTowardsASecondLife 的本地化字符串。
        /// </summary>
        internal static string SailingTowardsASecondLife {
            get {
                return ResourceManager.GetString("SailingTowardsASecondLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sampo 的本地化字符串。
        /// </summary>
        internal static string Sampo {
            get {
                return ResourceManager.GetString("Sampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScentAloneStaysTrue 的本地化字符串。
        /// </summary>
        internal static string ScentAloneStaysTrue {
            get {
                return ResourceManager.GetString("ScentAloneStaysTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seele 的本地化字符串。
        /// </summary>
        internal static string Seele {
            get {
                return ResourceManager.GetString("Seele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SeeYouAtTheEnd 的本地化字符串。
        /// </summary>
        internal static string SeeYouAtTheEnd {
            get {
                return ResourceManager.GetString("SeeYouAtTheEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serval 的本地化字符串。
        /// </summary>
        internal static string Serval {
            get {
                return ResourceManager.GetString("Serval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shadowburn 的本地化字符串。
        /// </summary>
        internal static string Shadowburn {
            get {
                return ResourceManager.GetString("Shadowburn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShadowedByNight 的本地化字符串。
        /// </summary>
        internal static string ShadowedByNight {
            get {
                return ResourceManager.GetString("ShadowedByNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SharedFeeling 的本地化字符串。
        /// </summary>
        internal static string SharedFeeling {
            get {
                return ResourceManager.GetString("SharedFeeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShatteredHome 的本地化字符串。
        /// </summary>
        internal static string ShatteredHome {
            get {
                return ResourceManager.GetString("ShatteredHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SheAlreadyShutHerEyes 的本地化字符串。
        /// </summary>
        internal static string SheAlreadyShutHerEyes {
            get {
                return ResourceManager.GetString("SheAlreadyShutHerEyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SilverWolf 的本地化字符串。
        /// </summary>
        internal static string SilverWolf {
            get {
                return ResourceManager.GetString("SilverWolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SleepLikeTheDead 的本地化字符串。
        /// </summary>
        internal static string SleepLikeTheDead {
            get {
                return ResourceManager.GetString("SleepLikeTheDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SolitaryHealing 的本地化字符串。
        /// </summary>
        internal static string SolitaryHealing {
            get {
                return ResourceManager.GetString("SolitaryHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SomethingIrreplaceable 的本地化字符串。
        /// </summary>
        internal static string SomethingIrreplaceable {
            get {
                return ResourceManager.GetString("SomethingIrreplaceable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sparkle 的本地化字符串。
        /// </summary>
        internal static string Sparkle {
            get {
                return ResourceManager.GetString("Sparkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SubscribeForMore 的本地化字符串。
        /// </summary>
        internal static string SubscribeForMore {
            get {
                return ResourceManager.GetString("SubscribeForMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sunday 的本地化字符串。
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sushang 的本地化字符串。
        /// </summary>
        internal static string Sushang {
            get {
                return ResourceManager.GetString("Sushang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SweatNowCryLess 的本地化字符串。
        /// </summary>
        internal static string SweatNowCryLess {
            get {
                return ResourceManager.GetString("SweatNowCryLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swordplay 的本地化字符串。
        /// </summary>
        internal static string Swordplay {
            get {
                return ResourceManager.GetString("Swordplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TextureOfMemories 的本地化字符串。
        /// </summary>
        internal static string TextureOfMemories {
            get {
                return ResourceManager.GetString("TextureOfMemories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TheBirthOfTheSelf 的本地化字符串。
        /// </summary>
        internal static string TheBirthOfTheSelf {
            get {
                return ResourceManager.GetString("TheBirthOfTheSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TheDayTheCosmosFell 的本地化字符串。
        /// </summary>
        internal static string TheDayTheCosmosFell {
            get {
                return ResourceManager.GetString("TheDayTheCosmosFell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TheFlowerRemembers 的本地化字符串。
        /// </summary>
        internal static string TheFlowerRemembers {
            get {
                return ResourceManager.GetString("TheFlowerRemembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TheForeverVictual 的本地化字符串。
        /// </summary>
        internal static string TheForeverVictual {
            get {
                return ResourceManager.GetString("TheForeverVictual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TheGreatCosmicEnterprise 的本地化字符串。
        /// </summary>
        internal static string TheGreatCosmicEnterprise {
            get {
                return ResourceManager.GetString("TheGreatCosmicEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TheHellWhereIdealsBurn 的本地化字符串。
        /// </summary>
        internal static string TheHellWhereIdealsBurn {
            get {
                return ResourceManager.GetString("TheHellWhereIdealsBurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TheHerta 的本地化字符串。
        /// </summary>
        internal static string TheHerta {
            get {
                return ResourceManager.GetString("TheHerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TheMolesWelcomeYou 的本地化字符串。
        /// </summary>
        internal static string TheMolesWelcomeYou {
            get {
                return ResourceManager.GetString("TheMolesWelcomeYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TheSeriousnessOfBreakfast 的本地化字符串。
        /// </summary>
        internal static string TheSeriousnessOfBreakfast {
            get {
                return ResourceManager.GetString("TheSeriousnessOfBreakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TheStorysNextPage 的本地化字符串。
        /// </summary>
        internal static string TheStorysNextPage {
            get {
                return ResourceManager.GetString("TheStorysNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TheUnreachableSide 的本地化字符串。
        /// </summary>
        internal static string TheUnreachableSide {
            get {
                return ResourceManager.GetString("TheUnreachableSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ThisIsMe 的本地化字符串。
        /// </summary>
        internal static string ThisIsMe {
            get {
                return ResourceManager.GetString("ThisIsMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ThoseManySprings 的本地化字符串。
        /// </summary>
        internal static string ThoseManySprings {
            get {
                return ResourceManager.GetString("ThoseManySprings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ThoughWorldsApart 的本地化字符串。
        /// </summary>
        internal static string ThoughWorldsApart {
            get {
                return ResourceManager.GetString("ThoughWorldsApart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ThusBurnsTheDawn 的本地化字符串。
        /// </summary>
        internal static string ThusBurnsTheDawn {
            get {
                return ResourceManager.GetString("ThusBurnsTheDawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimeWaitsForNoOne 的本地化字符串。
        /// </summary>
        internal static string TimeWaitsForNoOne {
            get {
                return ResourceManager.GetString("TimeWaitsForNoOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimeWovenIntoGold 的本地化字符串。
        /// </summary>
        internal static string TimeWovenIntoGold {
            get {
                return ResourceManager.GetString("TimeWovenIntoGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tingyun 的本地化字符串。
        /// </summary>
        internal static string Tingyun {
            get {
                return ResourceManager.GetString("Tingyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TodayIsAnotherPeacefulDay 的本地化字符串。
        /// </summary>
        internal static string TodayIsAnotherPeacefulDay {
            get {
                return ResourceManager.GetString("TodayIsAnotherPeacefulDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToEvernightsStars 的本地化字符串。
        /// </summary>
        internal static string ToEvernightsStars {
            get {
                return ResourceManager.GetString("ToEvernightsStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TopazNumby 的本地化字符串。
        /// </summary>
        internal static string TopazNumby {
            get {
                return ResourceManager.GetString("TopazNumby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TrendOfTheUniversalMarket 的本地化字符串。
        /// </summary>
        internal static string TrendOfTheUniversalMarket {
            get {
                return ResourceManager.GetString("TrendOfTheUniversalMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tribbie 的本地化字符串。
        /// </summary>
        internal static string Tribbie {
            get {
                return ResourceManager.GetString("Tribbie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnderTheBlueSky 的本地化字符串。
        /// </summary>
        internal static string UnderTheBlueSky {
            get {
                return ResourceManager.GetString("UnderTheBlueSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UntoTomorrowsMorrow 的本地化字符串。
        /// </summary>
        internal static string UntoTomorrowsMorrow {
            get {
                return ResourceManager.GetString("UntoTomorrowsMorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VictoryInABlink 的本地化字符串。
        /// </summary>
        internal static string VictoryInABlink {
            get {
                return ResourceManager.GetString("VictoryInABlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Void 的本地化字符串。
        /// </summary>
        internal static string Void {
            get {
                return ResourceManager.GetString("Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WarmthShortensColdNights 的本地化字符串。
        /// </summary>
        internal static string WarmthShortensColdNights {
            get {
                return ResourceManager.GetString("WarmthShortensColdNights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeAreWildfire 的本地化字符串。
        /// </summary>
        internal static string WeAreWildfire {
            get {
                return ResourceManager.GetString("WeAreWildfire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welt 的本地化字符串。
        /// </summary>
        internal static string Welt {
            get {
                return ResourceManager.GetString("Welt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeWillMeetAgain 的本地化字符串。
        /// </summary>
        internal static string WeWillMeetAgain {
            get {
                return ResourceManager.GetString("WeWillMeetAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WhatIsReal 的本地化字符串。
        /// </summary>
        internal static string WhatIsReal {
            get {
                return ResourceManager.GetString("WhatIsReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WhereaboutsShouldDreamsRest 的本地化字符串。
        /// </summary>
        internal static string WhereaboutsShouldDreamsRest {
            get {
                return ResourceManager.GetString("WhereaboutsShouldDreamsRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WhyDoesTheOceanSing 的本地化字符串。
        /// </summary>
        internal static string WhyDoesTheOceanSing {
            get {
                return ResourceManager.GetString("WhyDoesTheOceanSing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WoofWalkTime 的本地化字符串。
        /// </summary>
        internal static string WoofWalkTime {
            get {
                return ResourceManager.GetString("WoofWalkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorrisomeBlissful 的本地化字符串。
        /// </summary>
        internal static string WorrisomeBlissful {
            get {
                return ResourceManager.GetString("WorrisomeBlissful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xueyi 的本地化字符串。
        /// </summary>
        internal static string Xueyi {
            get {
                return ResourceManager.GetString("Xueyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yanqing 的本地化字符串。
        /// </summary>
        internal static string Yanqing {
            get {
                return ResourceManager.GetString("Yanqing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YetHopeIsPriceless 的本地化字符串。
        /// </summary>
        internal static string YetHopeIsPriceless {
            get {
                return ResourceManager.GetString("YetHopeIsPriceless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yukong 的本地化字符串。
        /// </summary>
        internal static string Yukong {
            get {
                return ResourceManager.GetString("Yukong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yunli 的本地化字符串。
        /// </summary>
        internal static string Yunli {
            get {
                return ResourceManager.GetString("Yunli", resourceCulture);
            }
        }
    }
}
