using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Text;

namespace SREmulator.SourceGeneration
{
    [Generator(LanguageNames.CSharp)]
    public class SRCharacterGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(SRKeysClassReceiver.Creator(SRKeys.SRCharacterKeys));
        }

        public void Execute(GeneratorExecutionContext context)
        {
            var receiver = (SRKeysClassReceiver)context.SyntaxContextReceiver;
            var semanticModel = context.Compilation.GetSemanticModel(receiver.Keys.SyntaxTree);
            var keys = Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetDeclaredSymbol(semanticModel, receiver.Keys);
            List<(string Key, int Rarity, bool Limited, string Type)> characters = new List<(string Key, int Rarity, bool Limited, string Type)>();

            foreach (var member in keys.GetMembers())
            {
                var attributeData = member.GetAttribute(SRAttributes.SRCharacterAttribute);
                string key = (string)attributeData.ConstructorArguments[0].Value;
                int rarity = (int)attributeData.ConstructorArguments[1].Value;
                bool limited = (bool)attributeData.ConstructorArguments[2].Value;

                string type;
                if (rarity is 5) type = limited ? "SRLimitedStar5Character" : "SRNonLimitedStar5Character";
                else type = "SRStar4Character";

                characters.Add((key, rarity, limited, type));
            }

            StringBuilder builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("namespace SREmulator.SRItems");
            builder.AppendLine("{");
            builder.AppendLine(1, "partial class SRCharacters");
            builder.AppendLine(1, "{");
            foreach (var character in characters)
            {
                builder.AppendLine(2, $"private static {character.Type} _{character.Key} = null;");
                builder.AppendLine(2, $"public static {character.Type} {character.Key} => _{character.Key} ??= new {character.Key}();");
            }
            builder.AppendLine(1, "    }");
            builder.AppendLine();

            foreach (var character in characters)
            {
                builder.AppendLine(1, $"public sealed record class {character.Key} : {character.Type}");
                builder.AppendLine(1, "{");
                builder.AppendLine(2, $"public override string Name => Localizations.Localization.{character.Key};");
                builder.AppendLine(1, "}");
                builder.AppendLine();
            }

            builder.AppendLine("}");

            context.AddSource("SRCharacters.g.cs", builder.ToString());
        }
    }
}
