//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SREmulator.GUI.Properties.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SREmulator.GUI.Properties.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 开发者: 的本地化字符串。
        /// </summary>
        public static string About_Developer {
            get {
                return ResourceManager.GetString("About_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者信息 的本地化字符串。
        /// </summary>
        public static string About_Developer_Title {
            get {
                return ResourceManager.GetString("About_Developer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用信息 的本地化字符串。
        /// </summary>
        public static string About_Info {
            get {
                return ResourceManager.GetString("About_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开源许可: 的本地化字符串。
        /// </summary>
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用名称: 的本地化字符串。
        /// </summary>
        public static string About_Name {
            get {
                return ResourceManager.GetString("About_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库链接: 的本地化字符串。
        /// </summary>
        public static string About_Url {
            get {
                return ResourceManager.GetString("About_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号 的本地化字符串。
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动更新检查 的本地化字符串。
        /// </summary>
        public static string Setting_AutoUpdate {
            get {
                return ResourceManager.GetString("Setting_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置: 的本地化字符串。
        /// </summary>
        public static string Setting_Language {
            get {
                return ResourceManager.GetString("Setting_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string Setting_Language_Chinese {
            get {
                return ResourceManager.GetString("Setting_Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Setting_Language_English {
            get {
                return ResourceManager.GetString("Setting_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置 的本地化字符串。
        /// </summary>
        public static string Setting_Save {
            get {
                return ResourceManager.GetString("Setting_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Setting_Title {
            get {
                return ResourceManager.GetString("Setting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新设置 的本地化字符串。
        /// </summary>
        public static string Setting_Update_Title {
            get {
                return ResourceManager.GetString("Setting_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新下载源: 的本地化字符串。
        /// </summary>
        public static string Setting_UpdateSource {
            get {
                return ResourceManager.GetString("Setting_UpdateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gitcode 的本地化字符串。
        /// </summary>
        public static string Setting_UpdateSource_Gitcode {
            get {
                return ResourceManager.GetString("Setting_UpdateSource_Gitcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github 的本地化字符串。
        /// </summary>
        public static string Setting_UpdateSource_Github {
            get {
                return ResourceManager.GetString("Setting_UpdateSource_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅计算平均抽数 的本地化字符串。
        /// </summary>
        public static string SimulateCard_CalculateAverage {
            get {
                return ResourceManager.GetString("SimulateCard_CalculateAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算配置抽取可能性 的本地化字符串。
        /// </summary>
        public static string SimulateCard_CalculateChance {
            get {
                return ResourceManager.GetString("SimulateCard_CalculateChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽卡配置 的本地化字符串。
        /// </summary>
        public static string SimulateCard_Config_Title {
            get {
                return ResourceManager.GetString("SimulateCard_Config_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果导出CSV 的本地化字符串。
        /// </summary>
        public static string SimulateCard_ExportCSV {
            get {
                return ResourceManager.GetString("SimulateCard_ExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在大保底 的本地化字符串。
        /// </summary>
        public static string SimulateCard_Guarantee {
            get {
                return ResourceManager.GetString("SimulateCard_Guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拥有无限抽卡资源 的本地化字符串。
        /// </summary>
        public static string SimulateCard_InfiniteResources {
            get {
                return ResourceManager.GetString("SimulateCard_InfiniteResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不计算抽卡副产物 的本地化字符串。
        /// </summary>
        public static string SimulateCard_NoReward {
            get {
                return ResourceManager.GetString("SimulateCard_NoReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡池版本: 的本地化字符串。
        /// </summary>
        public static string SimulateCard_PoolVersion {
            get {
                return ResourceManager.GetString("SimulateCard_PoolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有模拟结果均不准确，仅供参考 的本地化字符串。
        /// </summary>
        public static string SimulateCard_Result_Disclaimer {
            get {
                return ResourceManager.GetString("SimulateCard_Result_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽卡结果 的本地化字符串。
        /// </summary>
        public static string SimulateCard_Result_Title {
            get {
                return ResourceManager.GetString("SimulateCard_Result_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星轨专票: 的本地化字符串。
        /// </summary>
        public static string SimulateCard_StarRailPass {
            get {
                return ResourceManager.GetString("SimulateCard_StarRailPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星琼数量: 的本地化字符串。
        /// </summary>
        public static string SimulateCard_StellarJade {
            get {
                return ResourceManager.GetString("SimulateCard_StellarJade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽取目标: 的本地化字符串。
        /// </summary>
        public static string SimulateCard_Target {
            get {
                return ResourceManager.GetString("SimulateCard_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标配置 的本地化字符串。
        /// </summary>
        public static string SimulateCard_TargetConfig_Title {
            get {
                return ResourceManager.GetString("SimulateCard_TargetConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽取数量: 的本地化字符串。
        /// </summary>
        public static string SimulateCard_TargetCount {
            get {
                return ResourceManager.GetString("SimulateCard_TargetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光锥跃迁 的本地化字符串。
        /// </summary>
        public static string SimulateCard_Title {
            get {
                return ResourceManager.GetString("SimulateCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡池名称: 的本地化字符串。
        /// </summary>
        public static string SimulateCard_WarpName {
            get {
                return ResourceManager.GetString("SimulateCard_WarpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅计算平均抽数 的本地化字符串。
        /// </summary>
        public static string SimulateChara_CalculateAverage {
            get {
                return ResourceManager.GetString("SimulateChara_CalculateAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算配置抽取可能性 的本地化字符串。
        /// </summary>
        public static string SimulateChara_CalculateChance {
            get {
                return ResourceManager.GetString("SimulateChara_CalculateChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽卡配置 的本地化字符串。
        /// </summary>
        public static string SimulateChara_Config_Title {
            get {
                return ResourceManager.GetString("SimulateChara_Config_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果导出CSV 的本地化字符串。
        /// </summary>
        public static string SimulateChara_ExportCSV {
            get {
                return ResourceManager.GetString("SimulateChara_ExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在大保底 的本地化字符串。
        /// </summary>
        public static string SimulateChara_Guarantee {
            get {
                return ResourceManager.GetString("SimulateChara_Guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拥有无限抽卡资源 的本地化字符串。
        /// </summary>
        public static string SimulateChara_InfiniteResources {
            get {
                return ResourceManager.GetString("SimulateChara_InfiniteResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不计算抽卡副产物 的本地化字符串。
        /// </summary>
        public static string SimulateChara_NoReward {
            get {
                return ResourceManager.GetString("SimulateChara_NoReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡池版本: 的本地化字符串。
        /// </summary>
        public static string SimulateChara_PoolVersion {
            get {
                return ResourceManager.GetString("SimulateChara_PoolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有模拟结果均不准确，仅供参考 的本地化字符串。
        /// </summary>
        public static string SimulateChara_Result_Disclaimer {
            get {
                return ResourceManager.GetString("SimulateChara_Result_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽卡结果 的本地化字符串。
        /// </summary>
        public static string SimulateChara_Result_Title {
            get {
                return ResourceManager.GetString("SimulateChara_Result_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星琼数量: 的本地化字符串。
        /// </summary>
        public static string SimulateChara_StellarJade {
            get {
                return ResourceManager.GetString("SimulateChara_StellarJade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星轨专票: 的本地化字符串。
        /// </summary>
        public static string SimulateChara_StellarTicket {
            get {
                return ResourceManager.GetString("SimulateChara_StellarTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽取目标: 的本地化字符串。
        /// </summary>
        public static string SimulateChara_Target {
            get {
                return ResourceManager.GetString("SimulateChara_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标配置 的本地化字符串。
        /// </summary>
        public static string SimulateChara_TargetConfig_Title {
            get {
                return ResourceManager.GetString("SimulateChara_TargetConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽取数量: 的本地化字符串。
        /// </summary>
        public static string SimulateChara_TargetCount {
            get {
                return ResourceManager.GetString("SimulateChara_TargetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色跃迁 的本地化字符串。
        /// </summary>
        public static string SimulateChara_Title {
            get {
                return ResourceManager.GetString("SimulateChara_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡池名称: 的本地化字符串。
        /// </summary>
        public static string SimulateChara_WarpName {
            get {
                return ResourceManager.GetString("SimulateChara_WarpName", resourceCulture);
            }
        }
    }
}
